config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  post 'home/process_csvs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'csv_comparison'

class HomeController < ApplicationController
  def index
  end

  def process_csvs
    @account_discrepancies = CsvComparison.new.import(params[:file_one], params[:file_two], params[:concerns])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h3>Select two CSV files to upload</h3>
<div>
  <%= form_with url: home_process_csvs_path, local: true do |form| %>
    <div class="mb-3">
      <%= form.label :file, 'Upload CSV File', class: 'form-label' %>
      <%= form.file_field :file_one, class: 'form-control-file', required: true %>
    </div>
    <div class="mb-3">
      <%= form.label :file, 'Upload CSV File', class: 'form-label' %>
      <%= form.file_field :file_two, class: 'form-control-file', required: true %>
    </div>
    <div class="mb-3">
      <%= form.label :file, 'Concerns', class: 'form-label' %>
      <%= form.select :concerns, [['Both', 'both'], ['Subscriber Count', 'subscriber_count'], ['Channel Ownership', 'channel_ownership']], class: 'form-select' %>
    </div>
    <%= form.submit 'Upload CSV files', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/home/process_csvs.html.erb
<h3>Accounts with discrepancies</h3>
<div>
  <% if @account_discrepancies %>
    <% @account_discrepancies.each do |account| %>
      <div><%= account %></div>
    <% end %>
  <% else %>
    <p>There were no discrepancies between the two uploaded files</p>
  <% end %>
</div>
<div>
  <%= link_to 'Back', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Subscribers Checker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>